services:
  - type: web
    name: talentfit-backend
    env: python
    region: singapore
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: MONGODB_DB_NAME
        value: cvcover_db
