services:
  - type: web
    name: talentfit-backend
    env: docker
    region: singapore
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: MONGODB_DB_NAME
        value: cvcover_db
      - key: MONGODB_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
